### ISSUE TITLE
img2img is absent on this version

### ISSUE THREAD

**Issue by evtn** [fofr/cog-comfyui-sd3#1]
Previous cog had image and denoise parameters for img2img, but suddenly this repo had replaced the old one, without img2img capacity available.

Is this intended, and if not, will this be fixed?

**Comment by fofr** [comment]
Available now.

**Comment by sytpb** [comment]
how to prompt it to keep the orgainal photo features?  such as face features , I found img2img will change to another people , it doesnot be like the original .

**Comment by evtn** [comment]
img2img doesn't preserve such features, you will need another model (on top of sd3) for that, like InstantID

I'm not sure if this repo includes those, but the [original](https://github.com/fofr/cog-comfyui) one does, so probably you can use it there
